version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.6.47
    environment:
      MYSQL_DATABASE: userDB
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3344:3306      
    volumes:
      - mysql-data:/var/lib/mysql  

  spring:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - mysqldb
    environment:
      WAIT_HOSTS: mysqldb:3306
      DB_NAME: userDB
      DB_USER_NAME: root
      DB_PASS: root
    restart: on-failure

volumes:
  mysql-data: